package com.abikananda.ipo.analysis;
import com.abikananda.ipo.ai.IpoNarrativeAnalyzer; import com.abikananda.ipo.domain.*; import com.abikananda.ipo.repository.*; import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.core.task.TaskExecutor; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*;
@Service public class AnalysisOrchestrator {
 private final IpoRepository ipos; private final FinancialPeriodRepository financials; private final MarketSnapshotRepository markets; private final IpoValuationRepository valuations; private final IpoRiskRepository risks; private final IpoDocumentRepository documents; private final AnalysisRecordRepository history; private final AnalysisJobRepository jobs; private final IpoScoringService scoring; private final IpoNarrativeAnalyzer narrative; private final ObjectMapper json; private final TaskExecutor executor;
 public AnalysisOrchestrator(IpoRepository a,FinancialPeriodRepository b,MarketSnapshotRepository c,IpoValuationRepository d,IpoRiskRepository e,IpoDocumentRepository docs,AnalysisRecordRepository f,AnalysisJobRepository g,IpoScoringService h,IpoNarrativeAnalyzer narrative,ObjectMapper i,@Qualifier("applicationTaskExecutor") TaskExecutor x){ipos=a;financials=b;markets=c;valuations=d;risks=e;documents=docs;history=f;jobs=g;scoring=h;this.narrative=narrative;json=i;executor=x;}
 public AnalysisJob queue(Long ipoId){AnalysisJob j=AnalysisJob.builder().id(UUID.randomUUID().toString()).ipoId(ipoId).type(AnalysisJob.JobType.ANALYZE).status(AnalysisJob.JobStatus.QUEUED).createdAt(Instant.now()).build();jobs.save(j);executor.execute(()->run(j.getId()));return j;}
 public void run(String jobId){AnalysisJob j=jobs.findById(jobId).orElseThrow();j.setStatus(AnalysisJob.JobStatus.RUNNING);jobs.save(j);try{Ipo ipo=ipos.findById(j.getIpoId()).orElseThrow();String aiSummary=null,aiFailure=null;if(narrative.available()){Optional<IpoDocument> doc=documents.findByIpoIdOrderByRetrievedAtDesc(ipo.getId()).stream().filter(d->d.getExtractedText()!=null&&!d.getExtractedText().isBlank()).findFirst();if(doc.isPresent())try{var result=narrative.analyze(doc.get().getExtractedText());aiSummary=result.summary();storeAiRisks(ipo,doc.get(),result);}catch(Exception e){aiFailure=rootMessage(e);}else aiFailure="No extracted RHP/DRHP document is available for Ollama";}var fs=financials.findByIpoIdOrderByPeriodEndAsc(ipo.getId());var ms=markets.findTop30ByIpoIdOrderByObservedAtDesc(ipo.getId());Recommendation r=scoring.score(ipo,fs,ms.stream().findFirst().orElse(null),valuations.findByIpoId(ipo.getId()).orElse(null),risks.findByIpoIdOrderBySeverityAsc(ipo.getId()));String summary=aiSummary==null?r.summary():aiSummary+" "+r.summary();history.save(AnalysisRecord.builder().ipo(ipo).overallScore(r.overallScore()).confidenceScore(r.confidenceScore()).recommendation(r.recommendation()).listingRecommendation(r.listingGainRecommendation()).longTermRecommendation(r.longTermRecommendation()).engineVersion(narrative.available()?"deterministic-1+llm":"deterministic-1").scoringVersion("2026.09").scoreBreakdown(write(r.scoreBreakdown())).summary(summary).analyzedAt(Instant.now()).build());j.setStatus(aiFailure==null?AnalysisJob.JobStatus.COMPLETED:AnalysisJob.JobStatus.PARTIAL);j.setMessage(aiFailure==null?"Analysis completed":"Deterministic analysis completed; Ollama skipped: "+aiFailure);}catch(Exception e){j.setStatus(AnalysisJob.JobStatus.FAILED);j.setMessage(rootMessage(e));}j.setCompletedAt(Instant.now());jobs.save(j);}
 private void storeAiRisks(Ipo ipo,IpoDocument doc,IpoNarrativeAnalyzer.NarrativeResult result){Set<String> existing=new HashSet<>();risks.findByIpoIdOrderBySeverityAsc(ipo.getId()).forEach(r->existing.add(r.getDescription()));for(int i=0;i<result.risks().size();i++){String description=result.risks().get(i);if(description==null||description.isBlank()||existing.contains(description))continue;Integer page=i<result.pages().size()?result.pages().get(i):null;risks.save(IpoRisk.builder().ipo(ipo).severity(IpoRisk.Severity.MEDIUM).category("AI_DOCUMENT").description(description).documentPage(page).sourceUrl(doc.getSourceUrl()).hardOverride(false).build());}}
 private String rootMessage(Throwable e){Throwable x=e;while(x.getCause()!=null)x=x.getCause();return x.getMessage()==null?x.getClass().getSimpleName():x.getMessage();}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
}
