package com.abikananda.ipo.analysis;
import com.abikananda.ipo.domain.*; import com.abikananda.ipo.repository.*; import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.core.task.TaskExecutor; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*;
@Service public class AnalysisOrchestrator {
 private final IpoRepository ipos; private final FinancialPeriodRepository financials; private final MarketSnapshotRepository markets; private final IpoValuationRepository valuations; private final IpoRiskRepository risks; private final AnalysisRecordRepository history; private final AnalysisJobRepository jobs; private final IpoScoringService scoring; private final ObjectMapper json; private final TaskExecutor executor;
 public AnalysisOrchestrator(IpoRepository a,FinancialPeriodRepository b,MarketSnapshotRepository c,IpoValuationRepository d,IpoRiskRepository e,AnalysisRecordRepository f,AnalysisJobRepository g,IpoScoringService h,ObjectMapper i,@Qualifier("applicationTaskExecutor") TaskExecutor x){ipos=a;financials=b;markets=c;valuations=d;risks=e;history=f;jobs=g;scoring=h;json=i;executor=x;}
 public AnalysisJob queue(Long ipoId){AnalysisJob j=AnalysisJob.builder().id(UUID.randomUUID().toString()).ipoId(ipoId).type(AnalysisJob.JobType.ANALYZE).status(AnalysisJob.JobStatus.QUEUED).createdAt(Instant.now()).build();jobs.save(j);executor.execute(()->run(j.getId()));return j;}
 public void run(String jobId){AnalysisJob j=jobs.findById(jobId).orElseThrow();j.setStatus(AnalysisJob.JobStatus.RUNNING);jobs.save(j);try{Ipo ipo=ipos.findById(j.getIpoId()).orElseThrow();var fs=financials.findByIpoIdOrderByPeriodEndAsc(ipo.getId());var ms=markets.findTop30ByIpoIdOrderByObservedAtDesc(ipo.getId());Recommendation r=scoring.score(ipo,fs,ms.stream().findFirst().orElse(null),valuations.findByIpoId(ipo.getId()).orElse(null),risks.findByIpoIdOrderBySeverityAsc(ipo.getId()));history.save(AnalysisRecord.builder().ipo(ipo).overallScore(r.overallScore()).confidenceScore(r.confidenceScore()).recommendation(r.recommendation()).listingRecommendation(r.listingGainRecommendation()).longTermRecommendation(r.longTermRecommendation()).engineVersion("deterministic-1").scoringVersion("2026.09").scoreBreakdown(write(r.scoreBreakdown())).summary(r.summary()).analyzedAt(Instant.now()).build());j.setStatus(AnalysisJob.JobStatus.COMPLETED);j.setMessage("Analysis completed");}catch(Exception e){j.setStatus(AnalysisJob.JobStatus.FAILED);j.setMessage(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage());}j.setCompletedAt(Instant.now());jobs.save(j);}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
}
